= JavaScriptのPointerAnalysisに含まれる情報

ここではJavaScriptを解析した際の _PointerAnalysis_ から取得できる情報について説明する

(ここで扱う _PointerAnalysis_ は従来の _PointerAnalysis<InstanceKey>_ である)

== 基本的なクラスの説明

基本的にはJavaの場合と同じであるため、異なる箇所について説明する

=== _PointerKey_ クラス

抽象的なポインタを表すオブジェクト

オブジェクトの種類によって表現する派生クラスが異なり、
以下のクラスで表現される

==== _LocalPointerKey_ クラス

ローカル変数(ValueNumber)のポインタを表す

対応する _CGNode_ と ValueNumber の情報を持つ

==== _InstanceFieldKey_ クラス

Objectのプロパティのポインタ(式 x.y のyが指すもの)を表す

_InstanceFieldKey.getField()_ でこのプロパティの情報、
_InstanceFieldKey#getInstanceKey()_ でこのプロパティが属するObject(式 x.y のx)の _InstanceKey_ が取得できる

==== _TransitivePrototype_ クラス

オブジェクトがprototypeとして参照するオブジェクト一覧を表す

_TransitivePrototype#getInstanceKey()_ で対象とするオブジェクトの _InstanceKey_ が取得できる

==== _ReturnValueKey_ クラス

関数がreturnで返しうる値のポインタを表す

_CGNode_ の情報を持つ

==== _ExceptionReturnValueKey_ クラス (_ReturnValueKey_ の派生クラス)

関数がthrow等で返しうるエラーオブジェクト(TypeError等)のポインタを表す

==== _ObjectPropertyCatalog_ クラス

あるObjectが持つプロパティ名の一覧を表す

_ObjectPropertyCatalog#getObject()_ で一覧の対象とするObjectの _InstanceKey_ が取得できる

例えば、プロパティ名 a, b, d を持つObject objを対象としている場合、
この _ObjectPropertyCatalog_ が指す _InstanceKey_ は "a", "b", "d" の文字列定数を持ち、
_getObject()_ でobjのheap allocationを表す _InstanceKey_ が取得できる

==== _ReflectedField_ クラス

あるObjectをリフレクションとして参照できるオブジェクトの一覧を表す

例えば、Object objが obj.a = b であった場合、bというオブジェクトの _InstanceKey_ がこの _ReflectedField_ から参照できる

_ReflectedField#getInstanceKey_ で対象となるオブジェクトの _InstanceKey_ が取得できる。

==== _AstGlobalPointerKey_ クラス

大域オブジェクトを表す

_AstGlobalPointerKey#getName()_ で変数名が取得できる

==== _UpwardFunargPointerKey_ クラス (_AstGlobalPointerKey_ の派生クラス)

レキシカルスコープ変数を表す

_UpwardFunargPointerKey#getDefiningNode()_ で定義された _CGNode_ が取得できる +
(しかし、ローカルクラスなのでこのメソッドにアクセスできない)

=== _InstanceKey_ クラス

抽象的なheap locationを表すオブジェクト

オブジェクトの種類によって派生クラスが異なり、
以下のクラスで表現される

==== _GlobalObjectKey_ クラス

JavaScriptにおける大域オブジェクト global を表す

この _InstanceKey_ は1個だけ存在する

==== _NormalAllocationInNode_ クラス

通常のheap allocationを表す

==== _ScopeMappingInstanceKey_ クラス

クロージャ内で生成される関数の生成元(lexical parent)の情報を持つ

この _InstanceKey_ によって別々の呼び出しで生成されるクロージャ内関数を外部から呼び出した時に
区別することができる

_ScopeMappingInstanceKey#getBase()_ でクロージャ内で生成される関数を指す _InstanceKey_ が取得でき、
_ScopeMappingInstanceKey#getCreater()_ で生成元(lexical parent)の _CGNode_ が取得できる

[source, js]
.クロージャ内関数を区別する例: nested.js
----
function create(message) {
  function say() {
    console.log(message);
  }
  return say;
}

// ２つは同じクロージャ内関数 say だが、
// 生成元のCGNode(この場合はcreate関数のCGNode)によって別々の関数として区別される

hello = create('hello!');
hello(); // こっちのsayは "create('hello!')" のCGNodeに紐づく

goodbye = create('goodbye!');
goodbye(); // こっちのsayは "create('goodbye!')" のCGNodeに紐づく
----

==== _ConstantKey<T>_ クラス

定数を表し、その値の型はGeneric type Tに対応する

定数は _ConstantKey#getValue()_ で取得できる

===== _ConcreteTypeKey_ クラス

型オブジェクト(String, Array等)を表す
